---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: /vagrant/bliak.pem 

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu      
      hosts_output: public_dns
      key_files:
        - /vagrant/bliak.pem
suites:
  - name: default

